[build]
publish = "."

# ✅ CV : ne pas rediriger, juste servir le contenu du dossier /cv
[[redirects]]
from = "https://cv.zqsdev.com/*"
to = "/cv/:splat"
status = 200
force = true

# ✅ Calendly : redirection externe
[[redirects]]
from = "https://calendly.zqsdev.com/*"
to = "https://calendly.com/alexandre-zqsdev"
status = 301
force = true

# ✅ Domaine racine → GitHub
[[redirects]]
from = "https://zqsdev.com/*"
to = "https://github.com/aleqsd"
status = 301
force = true

# ✅ www. → GitHub aussi
[[redirects]]
from = "https://www.zqsdev.com/*"
to = "https://github.com/aleqsd"
status = 301
force = true
